// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPFUI_ToDoList.DbContexts;

#nullable disable

namespace WPFUI_ToDoList.Migrations
{
    [DbContext(typeof(WPFUI_ToDoListDBContext))]
    [Migration("20250226184621_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("WPFUI_ToDoList.DTOS.ToDoTaskDTO", b =>
                {
                    b.Property<Guid>("ToDoTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("TEXT");

                    b.HasKey("ToDoTaskID");

                    b.HasIndex("UserID1");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WPFUI_ToDoList.DTOS.UserDTO", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WPFUI_ToDoList.DTOS.ToDoTaskDTO", b =>
                {
                    b.HasOne("WPFUI_ToDoList.DTOS.UserDTO", "UserID")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
